baseURL = 'https://lowk.me/'
#baseURL = 'localhost'

name = "LowK"
title = "LowK"

theme = ["chringel-hugo-theme", "hugo-embed-pdf-shortcode"]
# https://github.com/chringel21/chringel-hugo-theme
# https://github.com/anvithks/hugo-embed-pdf-shortcode

languageCode = "en-us"
license = "MIT"

tags = ["Blog", "Blockchain", "Smart Contracts", "Security", "Auditor"]
features = ["Isso comments", "umami analytics", "SVG icons", "automatic dark mode", "deeplinks"]

paginate = 10
enableEmoji = true

# Third party
disqusShortname = 'lowk'

googleAnalytics = 'G-JDNP5HFPQ2'

# pdf short code
enableInlineShortcodes = true

[author]
  name = "LowK"

[module]
  [module.hugoVersion]
    extended = true
    min_version = "0.69"

[Params]
  headerTitle = 'lowk@dev: ~/$'
  name = "LowK"
  description = "Blockchain security auditor"
  footerCopyrightText = 'LowK 2023'

# for others mention me
[Params.webmentions]
  webmentionUrl = "https://webmention.io"
  webmentionEndpoint = "/webmention"
  webmentionPingbackEndpoint = "/xmlrcp"

# microformat2 h-card configuration
# All params except 'fullName' are optional
[Params.hcard]
  avatar = ""
  fullName = "Dat Lam Phat"
  pronouns = [ "he", "him" ]
  nickname = "LowK"
  showLocation = true
  city = "Ho Chi Minh city"
  region = "district 7"
  country = "Viet Nam"

# Social icons to be displayed on the front page
[[menu.social]]
  name = "GitHub"
  url = "https://github.com/lowk3v"

[[menu.social]]
  name = "Twitter"
  url = "https://twitter.com/lowk3v_"

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"