name: 'Netlify Deploy'

on:
  push:
    branches:
      - v4

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Netlify Rebuild'
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/${{ secrets.NETLIFY_TOKEN }}
        shell: bash
