name: 'Netlify Deploy'

on:
  release:
    types: [v4]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: 'Netlify Rebuild'
    steps:
      - uses: jogeleit/http-request-action@v1
        with:
          url: 'https://api.netlify.com/build_hooks/${{ secrets.NETLIFY_TOKEN }}'
          method: 'POST'
          customHeaders: '{"Content-Type": "application/json"}'
          data: '{}'
